Import Libraries

In [1]:
import pandas as pd
import sqlite3

Load the file

In [2]:
df = pd.read_excel("Cleaned_Dataset.xlsx")

df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

SQL Database

In [3]:
conn = sqlite3.connect("ecommerce.db")


Convert Excel Data into SQL Table

In [4]:
df.to_sql("orders", conn, if_exists="replace", index=False)

1200

SQL QUERIES

Query 1 - SELECT *

In [5]:
query = """
SELECT *
FROM orders
LIMIT 5
"""

pd.read_sql(query, conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15 00:00:00,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

Query 2 - SELECT Specific Columns

In [6]:
query = """
SELECT Product, TotalPrice
FROM orders
LIMIT 10
"""

pd.read_sql(query, conn)

   Product  TotalPrice
0  Monitor     2853.10
1    Phone      302.70
2   Tablet     2753.40
3    Chair      273.19
4  Printer     2504.04
5    Phone      491.72
6   Laptop      664.42
7  Monitor      747.75
8    Phone      268.56
9     Desk     2037.52

Query 3 - WHERE

In [7]:
query = """
SELECT *
FROM orders
WHERE PaymentMethod='Online'
LIMIT 10
"""

pd.read_sql(query, conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
1,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
2,ORD200011,2024-02-17 00:00:00,C93861,Monitor,3,49.14,831 Main St,Online,Returned,TRK48234646,7,SAVE10,Email,147.42
3,ORD200022,2023-01-29 00:00:00,C34416,Monitor,2,49.62,633 Main St,Online,Pending,TRK75937350,2,SAVE10,Google,99.24
4,ORD200024,2024-10-30 00:00:00,C17470,Laptop,2,230.95,956 Main St,Online,Delivered,TRK28775057,3,WINTER15,Referral,461.90
5,ORD200026,2024-03-06 00:00:00,C21944,Laptop,5,59.55,296 Main St,Online,Delivered,TRK80276812,6,No Coupon,Referral,297.75
6,ORD200027,2024-02-22 00:00:00,C97593,Printer,1,472.74,881 Main St,Online,Shipped,TRK89117573,6,WINTER15,Google,472.74
7,ORD200028,2023-11-21 00:00:00,C59823,Phone,4,160.07,568 Main St,Online,Pending,TRK65895539,5,No Coupon,Email,640.28
8,ORD200030,2025-03-22 00:00:00,C44267,Monitor,2,426.70,895 Main St,Online,Pending,TRK54751444,5,SAVE10,Referral,853.40
9,ORD200033,2023-06-05 00:00:00,C52184,Chair,1,162.77,912 Main St,Online,Cancelled,TRK73312471,4,WINTER15,Facebook,162.77

Query 4 - WHERE Product

In [14]:
query = """
SELECT *
FROM orders
WHERE Product='Printer'
LIMIT 10
"""

pd.read_sql(query, conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
1,ORD200015,2023-07-17 00:00:00,C39416,Printer,1,473.96,942 Main St,Cash,Delivered,TRK54930938,3,No Coupon,Google,473.96
2,ORD200016,2023-01-24 00:00:00,C28976,Printer,2,533.81,914 Main St,Credit Card,Pending,TRK13194259,3,FREESHIP,Email,1067.62
3,ORD200027,2024-02-22 00:00:00,C97593,Printer,1,472.74,881 Main St,Online,Shipped,TRK89117573,6,WINTER15,Google,472.74
4,ORD200039,2025-02-27 00:00:00,C96664,Printer,3,256.46,666 Main St,Credit Card,Delivered,TRK85508960,4,SAVE10,Referral,769.38
5,ORD200042,2024-05-06 00:00:00,C28712,Printer,2,151.66,980 Main St,Cash,Cancelled,TRK40772558,6,No Coupon,Instagram,303.32
6,ORD200049,2023-10-07 00:00:00,C11985,Printer,1,30.44,633 Main St,Credit Card,Shipped,TRK53272402,1,SAVE10,Email,30.44
7,ORD200055,2025-06-24 00:00:00,C95984,Printer,3,344.40,565 Main St,Online,Cancelled,TRK67434829,3,No Coupon,Facebook,1033.20
8,ORD200057,2023-01-22 00:00:00,C88036,Printer,5,314.27,842 Main St,Cash,Returned,TRK52470128,6,SAVE10,Instagram,1571.35
9,ORD200064,2025-06-25 00:00:00,C49720,Printer,3,130.61,752 Main St,Debit Card,Cancelled,TRK55785217,4,FREESHIP,Facebook,391.83

Query 5 - ORDER BY

In [8]:
query = """
SELECT OrderID, Product, TotalPrice
FROM orders
ORDER BY TotalPrice DESC
LIMIT 10
"""

pd.read_sql(query, conn)

     OrderID  Product  TotalPrice
0  ORD200789   Tablet     3456.40
1  ORD201122  Monitor     3390.95
2  ORD200632   Laptop     3390.80
3  ORD200469    Chair     3384.90
4  ORD200328   Tablet     3370.20
5  ORD200107  Printer     3353.75
6  ORD200326   Laptop     3352.40
7  ORD201065  Printer     3334.00
8  ORD201031    Phone     3322.55
9  ORD200463   Laptop     3313.90

Query 6 - COUNT

In [9]:
query = """
SELECT COUNT(*) AS TotalOrders
FROM orders
"""

pd.read_sql(query, conn)

   TotalOrders
0         1200

Query 7 - AVG

In [10]:
query = """
SELECT AVG(TotalPrice) AS AverageOrderValue
FROM orders
"""

pd.read_sql(query, conn)

   AverageOrderValue
0          1053.9683

Query 8 - SUM

In [11]:
query = """
SELECT SUM(TotalPrice) AS TotalRevenue
FROM orders
"""

pd.read_sql(query, conn)

   TotalRevenue
0    1264761.96

Query 9 - GROUP BY Product

In [12]:
query = """
SELECT Product,
COUNT(*) AS TotalOrders
FROM orders
GROUP BY Product
ORDER BY TotalOrders DESC
"""

pd.read_sql(query, conn)

   Product  TotalOrders
0  Printer          181
1   Tablet          179
2    Chair          178
3   Laptop          173
4     Desk          170
5  Monitor          163
6    Phone          156

Query 11 - GROUP BY Referral Source

In [13]:
query = """
SELECT ReferralSource,
COUNT(*) AS Customers
FROM orders
GROUP BY ReferralSource
ORDER BY Customers DESC
"""

pd.read_sql(query, conn)

  ReferralSource  Customers
0      Instagram        259
1          Email        250
2         Google        241
3       Facebook        228
4       Referral        222

# Conclusion

SQL queries such as SELECT, WHERE, ORDER BY, GROUP BY, COUNT, SUM, and AVG were successfully used to analyze the e-commerce dataset. The analysis helped identify product demand, payment preferences, referral source performance, and overall business metrics.